# Generated by Django 3.2 on 2021-04-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherToday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, unique=True)),
                ('min_t', models.IntegerField()),
                ('max_t', models.IntegerField()),
                ('type_weather', models.CharField(max_length=50)),
            ],
        ),
    ]
