# Generated by Django 3.2 on 2021-04-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathertoday',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='weathertoday',
            name='max_t',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='weathertoday',
            name='min_t',
            field=models.IntegerField(null=True),
        ),
    ]
