# Generated by Django 3.2 on 2021-04-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_auto_20210420_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weathertoday',
            name='max_t',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weathertoday',
            name='min_t',
            field=models.IntegerField(),
        ),
    ]
