# Generated by Django 3.2 on 2021-04-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_auto_20210421_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathertoday',
            name='main_t',
            field=models.IntegerField(null=True),
        ),
    ]
