# Generated by Django 3.2 on 2021-04-23 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_weathertoday_main_t'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherToday',
        ),
    ]
