# Generated by Django 3.2 on 2021-05-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0008_delete_weathertoday'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_min', models.IntegerField()),
                ('temp_max', models.IntegerField()),
                ('temp_main', models.IntegerField()),
                ('type_weather', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
