# Generated by Django 3.2 on 2021-07-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_weatherlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherlist',
            name='time',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
