# Generated by Django 3.2 on 2021-07-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_weatherlist_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherlist',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
